#!/bin/bash
base_path=~/scripts/vim_plugins
find ${base_path}/preinstall -name "*.sh" | xargs -I % bash -c %
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
find ${base_path}/postinstall -name "*.sh" | xargs -I % bash -c %
