#!/bin/bash
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
base_path=~/scripts/vim_plugins
find ${base_path} -name "*.sh" | xargs bash -c 
